apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eosc-webui
  namespace: rucio
  annotations:
    flux.weave.works/automated: "false"
spec:
  interval: 5m
  releaseName: eosc-webui
  chart:
    spec:
      chart: rucio-ui
      version: "1.26.0"
      sourceRef:
        kind: HelmRepository
        name: rucio-helm-repo
        namespace: rucio
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: db-secret
      valuesKey: values.yaml
  values:
    replicaCount: 1

    exposeErrorLogs: True

    service:
      type: NodePort
      useSSL: true
      port: 443
      targetPort: https
      portName: https

    image:
      repository: rucio/rucio-ui
      tag: release-1.25.7
      pullPolicy: Always

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

    additionalSecrets:
      idpsecrets:
        secretName: idpsecrets
        mountPath: /opt/rucio/etc/idpsecrets.json
        subPath: idpsecrets.json

      # w-rucio-redir:
      #   secretName: w-rucio-redir
      #   mountPath: /etc/httpd/conf.d/w_rucio_redir.conf
      #   subPath: w_rucio_redir.conf

    minReadySeconds: 5

    proxy:
      rucioProxy: "eosc-main.cern.ch"
      rucioProxyScheme: http
      rucioAuthProxy: "eosc-auth.cern.ch"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      path: /
      hosts:
        - "eosc-webui.cern.ch"

    config:
      policy:
        permission: "generic"
        schema: "generic"
        lfn2pfn_algorithm_default: "identity"

      oidc:
        idpsecrets: "/opt/rucio/etc/idpsecrets.json"
        admin_issuer: "escape"

    resources:
      limits:
        cpu: 100m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 500Mi
