apiVersion: ENC[AES256_GCM,data:k7c=,iv:bYpk5GL3D5mhGgISkbJqYlw8I7ftfnjvW8wXez7J4eE=,tag:Owd63ojwC+9mDAPsVeS5jg==,type:str]
kind: ENC[AES256_GCM,data:Q+8erS/x,iv:diX3viyyc0kfnpOc5NMCBRrae99KpBQYSN3T7RTEjos=,tag:z52I1yFUrYOYMCJ+3mTNQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DkIZSBZnm5Md,iv:0HxWDu2N9OjjW7dJ3g5Cvr+wA0UguV+PuxN6FaFT2/U=,tag:zAzri42mKTSk6XJfQpz7gA==,type:str]
    namespace: ENC[AES256_GCM,data:MCs7TJA=,iv:u89kvwnnXNfW2dJ9u0YufikKQ0FaqS7Jqkfyo5lRNDA=,tag:i3rKhV5J/9KRn5xanb+0Jg==,type:str]
type: ENC[AES256_GCM,data:uuGIl1tH,iv:NGFnwejtnVU8mDvKxUODXZUQS/9vRnqYeT/cFV6P6Gc=,tag:3cz7uZgJ+a5PXs99f9voUA==,type:str]
stringData:
    values.yaml: |-
        ENC[AES256_GCM,data:y8lwzeVZmvOHfpmJgRqlTUFPGOY4gPeJmGfFniuhy5xmV9EI5KioTMs3apcyHP29Kd9GiTzwpdYUjVFn3aWYAQrsft/FqXT31gH0T96carpSxEqhapCIBA+6+tSdMERA7IBFGs8Gahc=,iv:1FTB1f0XfXL7aJGeBXcvma+vpUBOGkRplhs0eunR0XI=,tag:Qf+ERDfWZfXX1U4BfPHtjQ==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C7BF20970A71ED7802E83EEADA11BEB6FF8B65C8
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA2w+4/M97hhLAQgAmf2OOh73XGmvng7XYgN7ZXNeJEvpa+s3y7rrUCHqr46x
            OsH046vES8w+1ULguU7pZszBKa+nec4rjhkKrMCnDQFD7xX8qlSlb1aUTCo9t+z3
            Ga6OB4Ss/TTWbGHKfA3KW5+NLDmlTM5HcsVQhjLhsEJ6yvPM/hg/qdgwYfkwCNnY
            7XgJrzS4sLKpWF281DP6q0dbwa5mz6pNogbOWitmPTNFWfQS7H7MK5IuUV2ePG4p
            EGg9e2U+N/HO3yveIHMd2NT1H9eAtHNLxx3crSESHJD5UyQ9BVFaBfhcl2sTBKhk
            hEjp+3rIH77JnA+lA716TdYG2js6jlODFyOOX0BUG9JeAZld01YWoKzUSQgNLU0e
            PqtbgEg8D0L80e46Szae8DbQ5wMmASkqjeyZspo/w3yhP1HaW4be9UQ+Y4nhVTQO
            aMGy3W1s1UZa/gi61uR2FqHLDHY6DqVVD6jwFwUh0w==
            =885z
            -----END PGP MESSAGE-----
        created_at: '2022-06-14T13:28:04Z'
    lastmodified: '2022-06-14T13:28:04Z'
    mac: ENC[AES256_GCM,data:WNTzvk+FoQGIGFmTYoXki/mKh8f3h7rYzzcN6Kfdlz+BjRUduOsIwofc/xnVZdxrNK3ftqNsw08gs+91EK738bPiaC/rvXqeArl2bFxkR6+G+GrHBDWVGezvNB9Z38/fUjOTIhkeScwnyO3PZUhpfMvHPDdsNTq5kA5P5d/rIhg=,iv:763NkvQpokpXFsNl6zx3DRqo8evEZmfiOn+elN52vcU=,tag:r34qmiCxbpusUpgThW4V7Q==,type:str]
