apiVersion: ENC[AES256_GCM,data:GBE=,iv:WRrMw5Rw51iG7/GExUeibQ+z/vuFLNRha9pUQPLDEX4=,tag:TXoKyQxs4Urj/hZxWcREEg==,type:str]
stringData:
    values.yaml: |-
        ENC[AES256_GCM,data:Psl9cHFSJFpnRSjnI4ts5VvvgVejX39p+mCsVmtcnNkd/gnBl1g+jMpjFr0EJ56S7VRsDra1Xfkhe2s9qgm+/1Yz0KnpEX6AEIApJI3oG0w8dwQjFQ4NRI2DOoiJ73AA59CojDvAs+LMWBcMQcFlbUYFoVOxpbvL,iv:MMaatjJ4dBakqLwmi1L4QWUH5TVNILqxDHfqiyTZEWY=,tag:SUUjH1l6Jz7dNcl9v5ovGg==,type:str]
kind: ENC[AES256_GCM,data:2Dqp8LeL,iv:/7ZiMtVGfYvnISlOw/72JXD+9y933CD/zcPL1sx/cus=,tag:d3jVpAYLIKzxfvwyFMbgrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tGgy+JDpxIop,iv:gVm7KNs4Lh0N7ViKKDtwoBGVsJhWaiSWuPZx1d0Dgtg=,tag:2Z0Cf/qOq40RZ3ah7I6iwQ==,type:str]
    namespace: ENC[AES256_GCM,data:GY3FGi4=,iv:zsSJlChhcwsksrFMJH9flXvOIQX+CNGoVpmtAECZ4IU=,tag:QHH7f0RaOZWX+Y7GjIydLA==,type:str]
type: ENC[AES256_GCM,data:euY0hqQJ,iv:nkMeovFkIXG8UvA7EMNDnB2dPAVIxMZO0JjsoQFHOJs=,tag:Kj29LHOjntor4fLS7/4pJg==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 16EC5E992C960E2C70247E8D59C30697AA845DA0
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1be3woFp4HRAQgAjrnvhO4wFl0cMEOrzlTE9foxIQxPM27mmIKk0P1Okko8
            tJHFkBJE/ycaKx7J9AK95KHnQBLAfM33GtkpBY6Z+w9yYThqfnJFOreSVBBH+xLL
            PIJcdIW2IXoHd1E7EHEA2ISp4JgrfMfSCR79zLAFvi546eZYhmiN1v9fgt+gKuFC
            RHn4HAx+XCXzCDFZII3XlCgODut+w0JAiTnm50oEKLBtkH0hLyEOiTk70IlLvzb1
            6jmsiz43TpTwZEbCQ3XUrgPM8yWUy9mQ5LrjaIfoUCwNbBbBF6x5u6B9Jq9nIYxQ
            +A9iIha+acNY4hr/YZEJT+7jxa4o3yAV2Ojoavmn69JeAQg7Ifw4DUiYxzki2RL7
            7RU2wUq+6z2i+Eom69+Hb3wRzimeoZomqqdQsetEtRk92n8QdhWnT1DrgBRmd0hB
            wG8GF5Y/TlW4m4OwlSl0C+k9/3t849Cm1a8/EkTjgg==
            =Meg9
            -----END PGP MESSAGE-----
        created_at: '2022-06-22T11:43:27Z'
    lastmodified: '2022-06-22T11:43:27Z'
    mac: ENC[AES256_GCM,data:+6MxL3EOp6pULK5G41rEW3xPIAM1H77MM7hREHU+omLECtLB/HzqvrBr+PWApFPwgS3slWnwiCqT4wGq921wr+SRiiWM8RQqlUYh+CgCKX3ZSZriixOezYg2Fo48vBl6LJLSR+sPqvF4uL784S2VbZjtzYPSe68IqfzpqSSiAAY=,iv:2DHisOSGg5RQxK6PWmXxLek40KRqmm93KIzG56yyaug=,tag:HbWfBsI7q92O5WJ+q+BzvQ==,type:str]
