apiVersion: ENC[AES256_GCM,data:RNU=,iv:HWG3ImSPElwPVocmt3JZVLRzF++iiLm/Eyu45QeUYv8=,tag:pkzOnOMRTTr0yutCsj9ICw==,type:str]
data:
    idpsecrets.json: ENC[AES256_GCM,data:OqlK3cl5YdBz3WNGHgExUxeuPhslBrm7pXy7orP5eecbbLMdljNw6/0W4Nf6gCmp+DE1tuSr1/MQg9qT4/MElyZXDtJDdE6G8EO823TuAWLJpgw7fHpGopsRzfwzSHU9462iPmLgCT4qHnVhQ0CiaVVWJNdI2Dk4Neoxze4hiq1/sH/H4v1MndNwPD/+APpg/lh5Giw8pwtgGd3PdORLArwBsEnAfgb4Nk6a0Dt9W8s+j7hR7UhOY1PCL6+fpj5YtkIF2UyivAtLCxDN91aLcGslOvbFSVGgJh2rkQf9mBsqcgVZiJaOjpnNlGqXwuA2axKlyhpRjwQRZo6Gd74EHz4QKwTJ3cmnQ6Nmnp/fLKhodEYm9NcPvU6tNiEWkW8xcAL/Sd/CbLwe3Ly3ORJQX26Kw/6gDLZGyPlTaVLVso0YzGj7chQtP9dut1gfbpuFxeeiweGOqgCKQYJVOLaCzh2O8ZoCyHGYm/WhcxpiZo35fqtVAWPTTRMjYmcZznS6iWLIefXZuBgBY6XJkg4m2R5P4cNO9Woop45IJwn5MohYvfTpj5Ni5MLrLbjKu+BrdTpA/PEknRj4YBr09Qe0HGys6r4B58hGAe1UUjxjVhPRkMRFGy9zAAaqavNx36Y1sOM+eXiJl2TmkyD8qQp0kl7P2U+W2PyfLvNF6yFzWd75EbDSOjDl0R1GGenJu8OcC7hM+5o+0WqqWSR0L1uQtzb3ICg+Hhd4qqsh+t67HQh+jbpwgaYEfjImtJHSwFW/B9wzKqj0A/XovMouPj6T69ZxWsqtCxEYlDnIsJj2CunKMgYS46d2/qwvmsnHxnxjswE8Cb3ESl4BHi1a3NEyc2zuQi6ULehsI2Fnxq6LrIwKxD2P8ueRXpLvv1Yf2dpF44c+8+cR0bRKoP65G9FQU+D/FAE/+qDbj+z1us1hIyxWrsh70EgmgDwir1zmubPsKE5LAtITCjcIbkW6YhNXACjzvyyP5md9fFxwp49S2luJh1vc905dENPFEmKeO7Xd07DwLDQw4Cm3T67TN80N4mDjQwDsRn9YQntJMjS7Y+dKtV3msq2FDcHWGpA=,iv:juxvMJSX0J7ILDJGre+a2COi64Puff9mQVApKLJXFEU=,tag:us2+QmAejfSbrxCqEEKkKQ==,type:str]
kind: ENC[AES256_GCM,data:QG9qsDV/,iv:jU2aG2JqFmjQhqG9raDB+u79+m1TzFSzpDhphoWKWtY=,tag:pNReqJZFKbYVPf/h+vyV+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ivWUBsfE4Ikr9XIPjSxjm9b756Q+TgQ=,iv:/LB94F5LXsm/ELBY0qsmltjsI1DknIdl0AjGaeD77bE=,tag:Lx/Qjde39FEOC46B6jshXA==,type:str]
    namespace: ENC[AES256_GCM,data:6TlgaKE=,iv:l9oB8FJJUFmG1a7g8zLyAeS7uOWl68OiiWXVL3yeV+4=,tag:Fv9k/x9oYOGuYKxGbTnspw==,type:str]
type: ENC[AES256_GCM,data:ye233ceI,iv:snNBscn7yFd58r9xPKgfB7afwX+TJC3NNFApYxfZ774=,tag:lWu1LSAvoeocjru9ZdXeYg==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: C7BF20970A71ED7802E83EEADA11BEB6FF8B65C8
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA2w+4/M97hhLAQf9Gq9uPhdTa02HjxPp66b0nG9hV8Pqg4Wuu4ATxvzj7k0B
            EkRoEIgE3J6yhnHpqoZOuSWKmnFCWMEz5AVyAFhF5hIBb/2hYsnI6p2QOsSSfE1a
            TSbEQP8delsTHrhWAE8SAQSXumCIUfaggCr00E308lhOEhiPqtlQ6FfTWuTAhvCZ
            A0ecQjL9i01AJ4fAibswcHNwOlFN9YQG2CqvGiI2TH5YAebQWXhUmUc2WRdQjIPd
            EfKlxYpu3blT9HuiGiF/QohHv7fjmb7xjCjf0CYQRm0QUvz548Y01G4FGDQqcepC
            +cV9AzkYMezEb3m0LosfVwBWy8YVhRm80lMSINfcnNJeAfqiFw+13vm8W7yeLq6e
            xPfMMU/Vyhc1p3CqF54EnYonTN3gUZwyql9o1Md00EagJmoFEBPERCrI11e/IWXs
            fnMgpqho4u6qlAO9iQ9zk36QaqyXmGdhbT45YFFjeA==
            =CKPi
            -----END PGP MESSAGE-----
        created_at: '2022-06-14T13:28:14Z'
    lastmodified: '2022-06-14T13:28:14Z'
    mac: ENC[AES256_GCM,data:JXJlavdpTS5+94l7+ggqM1WYmPP1Cl9/KDm0xJX8HQGML0IU9t+jQ/wLBk3TJcWpydS1z6GYNHd1L9E2nSaM1BqQV28opimClnDKl3rbCFp7C9Dk7PY/vjDESTOmdOtq59ew9n3BN2vKuR1tGcbYL+2hQTOjC6863pnYE3AfMVE=,iv:ape7EnrdoMomxS7m5DMkYF2/AG0JkxoK8abzwNoBJ6U=,tag:ge3N2oY2MPLNVqmpVIyTdQ==,type:str]
