apiVersion: v1
data:
  rse-accounts.cfg: ewogICAgIjA5NWQ0ZDQ5NTBkYzQ3MzI5MDk3YzBmNTUyN2VmMmIyIjogewogICAgICAgICJhY2Nlc3Nfa2V5IjogIjVlOGRmM2E4NWE2ODQ0ZTJhODkzOTEyYTNmMzQ5YWMyIiwKICAgICAgICAic2VjcmV0X2tleSI6ICIwNGE5NmEzOTk2MzQ0MzliYmE5ZmUyYzdjNGEzYmE0MSIsCiAgICAgICAgInNpZ25hdHVyZV92ZXJzaW9uIjogInMzdjQiLAogICAgICAgICJyZWdpb24iOiAiZXUtd2VzdC0zIgogICAgfSwKICAgICJiYWU5ODY4ZTA2OTY0NjVmOGZkNTNlYzY4ZjgxYmZhYSI6IHsKICAgICAgICAiYWNjZXNzX2tleSI6ICIxZGVjMmZlMmVkZmU0ZTZmYTM4ZTc5MDYzOTViYTU5MCIsCiAgICAgICAgInNlY3JldF9rZXkiOiAiZDc1Njk3Y2Q5ZjE0NDRmZTgyYWQ5OThiMzBlZmY4NjIiLAogICAgICAgICJzaWduYXR1cmVfdmVyc2lvbiI6ICJzM3Y0IiwKICAgICAgICAicmVnaW9uIjogIk5MIgogICAgfQp9Cg==
kind: Secret
metadata:
  name: eosc-servers-rse-accounts
  namespace: rucio
type: Opaque
